// Extracted from App.jsx in Phase 0 of docs/ARCHITECTURE-PLAN.md (D-37, 2026-06-10).
// Code is verbatim from the single-file era; comments may reference old App.jsx line numbers.
import { createClient } from "@supabase/supabase-js";
import { clientSummary, monthlyRows } from "../utils/finance.js";

/* ── SUPABASE CLIENT ─────────────────────────────────────────────────────── */
const SUPABASE_URL=(typeof import.meta!=="undefined"&&import.meta.env?import.meta.env.VITE_SUPABASE_URL:"")||"";
const SUPABASE_ANON_KEY=(typeof import.meta!=="undefined"&&import.meta.env?import.meta.env.VITE_SUPABASE_ANON_KEY:"")||"";
const supabase=(SUPABASE_URL&&SUPABASE_ANON_KEY)?createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true}}):null;
async function gaLoadClients(userId){if(!supabase||!userId)return null;const{data,error}=await supabase.from("clients").select("data").eq("user_id",userId).is("deleted_at",null);if(error){console.error("[GA] load clients error",error);return null;}const _rows=(data||[]).map(r=>r.data);const _seen=new Set();const _out=[];for(const _c of _rows){const _k=_c&&_c.id;if(_k==null){_out.push(_c);continue;}if(_seen.has(_k))continue;_seen.add(_k);_out.push(_c);}return _out;}
async function gaSaveClient(userId,clientObj){if(!supabase||!userId||!clientObj?.id)return false;const localId=String(clientObj.id);const _fail=()=>{if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("ga-save-failed",{detail:{which:"client"}}));return false;};try{let existingId=null;const{data:byLocal,error:e1}=await supabase.from("clients").select("id").eq("user_id",userId).eq("local_id",localId).is("deleted_at",null).limit(1);if(e1){console.error("[GA] find client error (local_id)",e1);return _fail();}if(byLocal&&byLocal[0])existingId=byLocal[0].id;else{const{data:byBlob,error:e2}=await supabase.from("clients").select("id").eq("user_id",userId).eq("data->>id",localId).is("deleted_at",null).limit(1);if(e2){console.error("[GA] find client error (blob id)",e2);return _fail();}if(byBlob&&byBlob[0])existingId=byBlob[0].id;}const payload={user_id:userId,local_id:localId,data:clientObj,...clientSummary(clientObj)};const{error}=existingId?await supabase.from("clients").update(payload).eq("id",existingId).eq("user_id",userId):await supabase.from("clients").insert(payload);if(error){console.error("[GA] save client error",error);return _fail();}try{const _mrows=monthlyRows(clientObj).map(r=>({user_id:userId,client_local_id:localId,...r}));if(_mrows.length)await supabase.from("client_monthly_summary").upsert(_mrows,{onConflict:"user_id,client_local_id,month_key"});}catch(_me){console.error("[GA] monthly summary upsert error",_me);}return true;}catch(e){console.error("[GA] save client exception",e);return _fail();}}
async function gaDeleteClient(userId,clientId){if(!supabase||!userId||!clientId)return;const cid=String(clientId);const stamp={deleted_at:new Date().toISOString()};const r1=await supabase.from("clients").update(stamp).eq("user_id",userId).is("deleted_at",null).eq("local_id",cid);if(r1.error)console.error("[GA] delete client error (local_id)",r1.error);const r2=await supabase.from("clients").update(stamp).eq("user_id",userId).is("deleted_at",null).eq("data->>id",cid);if(r2.error)console.error("[GA] delete client error (blob id)",r2.error);}
async function gaLoadSettings(userId){if(!supabase||!userId)return null;const{data,error}=await supabase.from("settings").select("data").eq("user_id",userId).maybeSingle();if(error){console.error("[GA] load settings error",error);return null;}return data?.data||null;}
async function gaSaveSettings(userId,settingsObj){if(!supabase||!userId)return;const{error}=await supabase.from("settings").upsert({user_id:userId,data:settingsObj},{onConflict:"user_id"});if(error){console.error("[GA] save settings error",error);if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("ga-save-failed",{detail:{which:"settings"}}));}}
async function gaLoadIntakeSubmissions(advisorId){if(!supabase||!advisorId)return[];try{const{data,error}=await supabase.from("intake_submissions").select("*").eq("advisor_id",advisorId).order("created_at",{ascending:false}).limit(200);if(error){console.error("[GA] load intake subs error",error);return[];}return data||[];}catch(e){console.error("[GA] load intake subs exception",e);return[];}}
async function gaSubmitIntake(advisorId,lang,formData){if(!supabase||!advisorId)return{ok:false,error:"no-supabase"};try{const token="tok_"+Math.random().toString(36).slice(2,14)+Date.now().toString(36);const payload={advisor_id:advisorId,submission_token:token,lang:lang||"en",status:"pending",data:formData,user_agent:typeof navigator!=="undefined"?String(navigator.userAgent||"").slice(0,200):""};const{data,error}=await supabase.from("intake_submissions").insert(payload).select("id").single();if(error){console.error("[GA] intake submit error",error);return{ok:false,error:error.message};}return{ok:true,token,submissionId:data&&data.id};}catch(e){console.error("[GA] intake submit exception",e);return{ok:false,error:String(e&&e.message||e)};}}
async function gaUpdateIntakeStatus(id,patch){if(!supabase||!id)return false;try{const{error}=await supabase.from("intake_submissions").update(patch).eq("id",id);if(error){console.error("[GA] intake update error",error);return false;}return true;}catch(e){console.error("[GA] intake update exception",e);return false;}}
async function gaUpdateIntakeData(id,data){if(!supabase||!id)return false;try{const{error}=await supabase.from("intake_submissions").update({data}).eq("id",id);if(error){console.error("[GA] intake data update error",error);return false;}return true;}catch(e){console.error("[GA] intake data update exception",e);return false;}}
async function gaDeleteIntakeSubmission(id){if(!supabase||!id)return false;try{const{error}=await supabase.from("intake_submissions").delete().eq("id",id);if(error){console.error("[GA] intake delete error",error);return false;}return true;}catch(e){console.error("[GA] intake delete exception",e);return false;}}
async function gaDeleteIntakeSubmissionsByStatus(advisorId,status){if(!supabase||!advisorId||!status)return 0;try{const{data,error}=await supabase.from("intake_submissions").delete().eq("advisor_id",advisorId).eq("status",status).select("id");if(error){console.error("[GA] intake bulk delete error",error);return 0;}return (data||[]).length;}catch(e){console.error("[GA] intake bulk delete exception",e);return 0;}}
async function gaLoadIntakeInvites(userId){if(!supabase||!userId)return[];try{const{data,error}=await supabase.from("intake_invites").select("*").eq("user_id",userId).order("created_at",{ascending:false}).limit(200);if(error){console.error("[GA] load invites error",error);return[];}return data||[];}catch(e){console.error("[GA] load invites exception",e);return[];}}
async function gaDeleteIntakeInvite(id){if(!supabase||!id)return false;try{const{error}=await supabase.from("intake_invites").delete().eq("id",id);if(error){console.error("[GA] delete invite error",error);return false;}return true;}catch(e){console.error("[GA] delete invite exception",e);return false;}}
async function gaDeleteAllIntakeInvites(userId){if(!supabase||!userId)return false;try{const{error}=await supabase.from("intake_invites").delete().eq("user_id",userId);if(error){console.error("[GA] clear invites error",error);return false;}return true;}catch(e){console.error("[GA] clear invites exception",e);return false;}}
async function gaSendIntakeInvite(payload){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in. Please log out and back in."};const r=await fetch("/api/send-intake-invite",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status),detail:j};return{ok:true,...j};}catch(e){console.error("[GA] send invite exception",e);return{ok:false,error:String(e&&e.message||e)};}}
async function gaSendSupportEmail(payload){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in. Please log out and back in."};const r=await fetch("/api/send-support-email",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status),detail:j};return{ok:true,...j};}catch(e){console.error("[GA] send support exception",e);return{ok:false,error:String(e&&e.message||e)};}}
async function gaResolveIntakeInvite(token){try{const r=await fetch("/api/resolve-intake-invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"accept",token})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status)};return{ok:true,...j};}catch(e){console.error("[GA] resolve invite exception",e);return{ok:false,error:String(e&&e.message||e)};}}
async function gaMarkIntakeInviteSubmitted(token,submissionId){try{await fetch("/api/mark-intake-invite-submitted",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,submissionId})});}catch(e){console.error("[GA] mark invite submitted exception",e);}}
// ── Client Portal helpers (v0.68) ──────────────────────────────────────────
function genPortalToken(){const a=new Uint8Array(32);(typeof crypto!=="undefined"?crypto:window.crypto).getRandomValues(a);let b="";for(let i=0;i<a.length;i++)b+=String.fromCharCode(a[i]);return btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
async function gaResolvePortal(token){try{const r=await fetch("/api/resolve-portal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"accept",token})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status)};return{ok:true,...j};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}
async function gaListPortalLinks(userId,clientLocalId){if(!supabase||!userId)return[];try{let q=supabase.from("portal_links").select("*").eq("user_id",userId).order("created_at",{ascending:false});if(clientLocalId)q=q.eq("client_local_id",String(clientLocalId));const{data,error}=await q;if(error){console.error("[GA] list portal links",error);return[];}return data||[];}catch(e){console.error("[GA] list portal links exception",e);return[];}}
async function gaCreatePortalLink(userId,clientLocalId,opts){if(!supabase||!userId||!clientLocalId)return{ok:false,error:"no-supabase"};try{const token=genPortalToken();const row={user_id:userId,client_local_id:String(clientLocalId),token,label:(opts&&opts.label)||null,expires_at:(opts&&opts.expiresAt)||null,modules:(opts&&opts.modules)||null};const{data,error}=await supabase.from("portal_links").insert(row).select("*").single();if(error){console.error("[GA] create portal link",error);return{ok:false,error:error.message};}return{ok:true,link:data,token};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}
async function gaSendPortalLink(payload){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in. Please log out and back in."};const r=await fetch("/api/send-portal-link",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status)};return{ok:true,...j};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}
async function gaRevokePortalLink(id){if(!supabase||!id)return false;try{const{error}=await supabase.from("portal_links").update({revoked:true}).eq("id",id);if(error){console.error("[GA] revoke portal link",error);return false;}return true;}catch(e){return false;}}
async function gaEmailCompleteReport(payload){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in. Please log out and back in."};const r=await fetch("/api/render-report-pdf",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status),detail:j};return{ok:true,...j};}catch(e){console.error("[GA] email report exception",e);return{ok:false,error:String(e&&e.message||e)};}}
// v0.51 — download path uses the same Puppeteer warm-PDF render as the email
// path, just returns the binary instead of attaching it to a Resend send.
// Same artifact, two distribution channels.
async function gaDownloadCompleteReport(payload){
  if(!supabase)return{ok:false,error:"no-supabase"};
  try{
    const{data:sess}=await supabase.auth.getSession();
    const jwt=sess?.session?.access_token;
    if(!jwt)return{ok:false,error:"Not signed in. Please log out and back in."};
    const r=await fetch("/api/render-report-pdf",{
      method:"POST",
      headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},
      body:JSON.stringify({...payload,mode:"download"})
    });
    if(!r.ok){
      const j=await r.json().catch(()=>({}));
      return{ok:false,error:j.error||("HTTP "+r.status)};
    }
    const ct=r.headers.get("Content-Type")||"";
    if(!/^application\/pdf/i.test(ct)){
      return{ok:false,error:"Server returned "+ct+" (expected application/pdf)"};
    }
    const blob=await r.blob();
    const cd=r.headers.get("Content-Disposition")||"";
    const m=cd.match(/filename="([^"]+)"/);
    const filename=m?m[1]:"golden-anchor-report.pdf";
    const url=URL.createObjectURL(blob);
    const a=document.createElement("a");
    a.href=url;a.download=filename;a.style.display="none";
    document.body.appendChild(a);a.click();
    setTimeout(()=>{document.body.removeChild(a);URL.revokeObjectURL(url);},250);
    return{ok:true,filename};
  }catch(e){
    console.error("[GA] download report exception",e);
    return{ok:false,error:String(e&&e.message||e)};
  }
}
async function gaMigrateLocalStorage(userId){if(!supabase||!userId)return false;if(localStorage.getItem("ga_migrated_to_supabase")==="1")return false;try{const lsClients=localStorage.getItem("ga_v3");const lsSettings=localStorage.getItem("ga_settings");const existing=await gaLoadClients(userId);if((existing||[]).length>0){localStorage.setItem("ga_migrated_to_supabase","1");return false;}let allOk=true;let savedCount=0;let totalCount=0;if(lsClients){const arr=JSON.parse(lsClients);if(Array.isArray(arr)&&arr.length>0){totalCount=arr.length;for(const c of arr){const ok=await gaSaveClient(userId,c);if(ok)savedCount++;else allOk=false;}}}if(lsSettings){try{const s=JSON.parse(lsSettings);await gaSaveSettings(userId,s);}catch(se){console.error("[GA] settings migrate error",se);}}if(allOk&&totalCount===savedCount){localStorage.setItem("ga_migrated_to_supabase","1");console.log(`[GA] migration complete: ${savedCount}/${totalCount} clients migrated`);return true;}else{console.error(`[GA] migration incomplete: ${savedCount}/${totalCount} clients saved — flag NOT set, will retry next login`);return false;}}catch(e){console.error("[GA] migration error",e);return false;}}
function gaClearLocalCache(){try{["ga_v3","ga_settings","ga_session_draft","ga_migrated_to_supabase","ga_cache_uid"].forEach(k=>localStorage.removeItem(k));}catch(e){}}
// v0.75 — choose-your-price Premium checkout (server creates/reuses the price + session)
async function gaPremiumCheckout(amount){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in."};const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify({action:"checkout",amount})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,code:j.code,error:j.error||("HTTP "+r.status)};return{ok:true,url:j.url};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}
// v0.75 — master/members admin (list = admin allowlist; grant/revoke = any advisor)
async function gaAdminMembers(payload){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in."};const r=await fetch("/api/admin-members",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status)};return{ok:true,...j};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}

// ── Account links (MD-C Link-R, v0.76) ─────────────────────────────────────
async function gaCreateClientLink(userId,clientLocalId,invitedEmail){if(!supabase||!userId)return{ok:false,error:"no-supabase"};try{const token=genPortalToken();const{data,error}=await supabase.from("client_links").insert({advisor_uid:userId,client_local_id:String(clientLocalId),invited_email:invitedEmail.trim().toLowerCase(),token}).select().single();if(error)return{ok:false,error:error.message};return{ok:true,link:data};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}
async function gaListClientLinks(userId,clientLocalId){if(!supabase||!userId)return[];try{let q=supabase.from("client_links").select("*").eq("advisor_uid",userId).order("created_at",{ascending:false});if(clientLocalId!=null)q=q.eq("client_local_id",String(clientLocalId));const{data,error}=await q;if(error)return[];return data||[];}catch(e){return[];}}
async function gaRevokeClientLink(id){if(!supabase||!id)return false;try{const{error}=await supabase.from("client_links").update({status:"revoked"}).eq("id",id);return !error;}catch(e){return false;}}
async function gaSendLinkInvite(payload){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in."};const r=await fetch("/api/link",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify({action:"invite-email",...payload})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status)};return{ok:true,...j};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}
async function gaAcceptLink(token){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in."};const r=await fetch("/api/link",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify({action:"accept",token})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status)};return{ok:true,...j};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}
async function gaLinkedOverview(){if(!supabase)return{ok:false,error:"no-supabase"};try{const{data:sess}=await supabase.auth.getSession();const jwt=sess?.session?.access_token;if(!jwt)return{ok:false,error:"Not signed in."};const r=await fetch("/api/link",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+jwt},body:JSON.stringify({action:"overview"})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{ok:false,error:j.error||("HTTP "+r.status)};return{ok:true,...j};}catch(e){return{ok:false,error:String(e&&e.message||e)};}}

// ── Scalable data layer (2026-06-24): paginated list, single-client load, dashboard RPCs ──
async function gaListClients(userId,{page=0,pageSize=50,sort="name",search="",archived=false}={}){if(!supabase||!userId)return{rows:[],total:0};let q=supabase.from("clients").select("local_id,first_name,last_name,partner_first,email,net_worth,total_debt,monthly_income,liquid_assets,snapshot_count,archived",{count:"exact"}).eq("user_id",userId).is("deleted_at",null).eq("archived",archived);if(search){const s=String(search).replace(/[%,.]/g,"").trim();if(s)q=q.or(`first_name.ilike.%${s}%,last_name.ilike.%${s}%,email.ilike.%${s}%`);}const ord=sort==="debt"?["total_debt",{ascending:false}]:sort==="income"?["monthly_income",{ascending:false}]:sort==="recent"?["last_activity",{ascending:false}]:["last_name",{ascending:true}];q=q.order(ord[0],ord[1]).range(page*pageSize,page*pageSize+pageSize-1);const{data,error,count}=await q;if(error){console.error("[GA] list clients error",error);return{rows:[],total:0};}return{rows:data||[],total:count||0};}
async function gaLoadClient(userId,localId){if(!supabase||!userId)return null;const{data,error}=await supabase.from("clients").select("data").eq("user_id",userId).eq("local_id",String(localId)).is("deleted_at",null).maybeSingle();if(error){console.error("[GA] load client error",error);return null;}return data?data.data:null;}
// v0.83.3 — load EVERY full blob for the advisor (export-all / backup-all). Pages past PostgREST's 1000-row
// cap so a large book exports completely. Read-only; never used on the per-client open path (that's gaLoadClient).
async function gaLoadAllClientBlobs(userId){if(!supabase||!userId)return [];const PAGE=1000;let from=0;const out=[];for(;;){const{data,error}=await supabase.from("clients").select("data").eq("user_id",userId).is("deleted_at",null).order("local_id",{ascending:true}).range(from,from+PAGE-1);if(error){console.error("[GA] load all blobs error",error);break;}const rows=(data||[]).map(r=>r.data).filter(Boolean);out.push(...rows);if(!data||data.length<PAGE)break;from+=PAGE;}const seen=new Set();const res=[];for(const c of out){const k=c&&c.id;if(k==null){res.push(c);continue;}if(seen.has(k))continue;seen.add(k);res.push(c);}return res;}
// v0.83 — load lightweight display-ready SUMMARY rows (no blobs) for the advisor list/roster; blobs load on open via gaLoadClient.
const _CPAL=["#C9A84C","#D97706","#3B82F6","#10B981","#8B5CF6","#06B6D4","#EF4444","#755023"];
const _sumColor=(id)=>{let h=0;const s=String(id||"");for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return _CPAL[h%_CPAL.length];};
const _SUMMARY_COLS="local_id,first_name,last_name,partner_first,email,client_type,net_worth,total_debt,monthly_income,liquid_assets,snapshot_count,last_activity,archived";
const _mapSummaryRow=(r)=>({id:r.local_id,firstName:r.first_name||"",lastName:r.last_name||"",partnerFirst:r.partner_first||"",email:r.email||"",clientType:r.client_type||"financeOnly",net_worth:+r.net_worth||0,total_debt:+r.total_debt||0,monthly_income:+r.monthly_income||0,liquid_assets:+r.liquid_assets||0,snapshot_count:r.snapshot_count||0,last_activity:r.last_activity,archived:!!r.archived,color1:_sumColor(r.local_id),_summary:true});
// v0.83.4 — page past PostgREST's 1000-row cap so a >1000-client advisor loads the FULL roster (was
// silently truncated at 1000). Ordered by local_id for stable paging. Error contract preserved: a
// first-page error returns null (so refreshSummaries keeps the current list on a transient error);
// a later-page error logs + returns the rows gathered so far (graceful partial rather than wiping all).
async function gaLoadClientSummaries(userId){if(!supabase||!userId)return null;const PAGE=1000;let from=0;const out=[];for(;;){const{data,error}=await supabase.from("clients").select(_SUMMARY_COLS).eq("user_id",userId).is("deleted_at",null).order("local_id",{ascending:true}).range(from,from+PAGE-1);if(error){console.error("[GA] load summaries error",error);if(from===0)return null;break;}out.push(...(data||[]));if(!data||data.length<PAGE)break;from+=PAGE;}return out.map(_mapSummaryRow);}
async function gaSetArchived(userId,localId,archived){if(!supabase||!userId)return false;const{error}=await supabase.rpc("ga_set_archived",{p_local_id:String(localId),p_archived:!!archived});if(error){console.error("[GA] set archived error",error);return false;}return true;}
// v0.83.2 — advisor reminders over summary + monthly tables (RLS-scoped). Restores noContact + highDSR +
// debtRising without loading blobs. Returns [] (none) or null (error → caller keeps its client-side fallback).
async function gaAdvisorReminders(noContactDays){if(!supabase)return null;const{data,error}=await supabase.rpc("ga_advisor_reminders",{p_no_contact_days:+noContactDays||30});if(error){console.error("[GA] advisor reminders error",error);return null;}return data||[];}
async function gaDashboardSummary(){if(!supabase)return null;const{data,error}=await supabase.rpc("ga_dashboard_summary");if(error){console.error("[GA] dash summary error",error);return null;}return data;}
async function gaDashboardTrend(){if(!supabase)return[];const{data,error}=await supabase.rpc("ga_dashboard_trend");if(error){console.error("[GA] dash trend error",error);return[];}return data||[];}
async function gaDashboardTopDebts(limit=20){if(!supabase)return[];const{data,error}=await supabase.rpc("ga_dashboard_top_debts",{p_limit:limit});if(error){console.error("[GA] dash top-debts error",error);return[];}return data||[];}
async function gaDashboardAssetAlloc(){if(!supabase)return[];const{data,error}=await supabase.rpc("ga_dashboard_asset_alloc");if(error){console.error("[GA] dash asset-alloc error",error);return[];}return data||[];}
async function gaDashboardClientDeltas(limit=12){if(!supabase)return[];const{data,error}=await supabase.rpc("ga_dashboard_client_deltas",{p_limit:limit});if(error){console.error("[GA] dash client-deltas error",error);return[];}return data||[];}
async function gaDashboardAll(){const[summary,trend,debts,assets,deltas]=await Promise.all([gaDashboardSummary(),gaDashboardTrend(),gaDashboardTopDebts(20),gaDashboardAssetAlloc(),gaDashboardClientDeltas(12)]);return{summary,trend,debts,assets,deltas};}
export { supabase, gaListClients, gaLoadClient, gaLoadAllClientBlobs, gaLoadClientSummaries, gaSetArchived, gaAdvisorReminders, gaDashboardSummary, gaDashboardTrend, gaDashboardTopDebts, gaDashboardAssetAlloc, gaDashboardClientDeltas, gaDashboardAll, gaLoadClients, gaSaveClient, gaDeleteClient, gaLoadSettings, gaSaveSettings, gaLoadIntakeSubmissions, gaSubmitIntake, gaUpdateIntakeStatus, gaUpdateIntakeData, gaDeleteIntakeSubmission, gaDeleteIntakeSubmissionsByStatus, gaLoadIntakeInvites, gaDeleteIntakeInvite, gaDeleteAllIntakeInvites, gaSendIntakeInvite, gaSendSupportEmail, gaResolveIntakeInvite, gaMarkIntakeInviteSubmitted, genPortalToken, gaResolvePortal, gaListPortalLinks, gaCreatePortalLink, gaSendPortalLink, gaRevokePortalLink, gaEmailCompleteReport, gaDownloadCompleteReport, gaMigrateLocalStorage, gaClearLocalCache, gaPremiumCheckout, gaAdminMembers, gaCreateClientLink, gaListClientLinks, gaRevokeClientLink, gaSendLinkInvite, gaAcceptLink, gaLinkedOverview };
