// Extracted from App.jsx in Phase 0 of docs/ARCHITECTURE-PLAN.md (D-37, 2026-06-10).
// Code is verbatim from the single-file era; comments may reference old App.jsx line numbers.
import { GOLD } from "../styles/theme";

/* ── META ─────────────────────────────────────────────────────────────────── */
const ACCT_META={checking:{l:"Checking",icon:"🏦",c:"#3B82F6",liquid:true},savings:{l:"Savings",icon:"💵",c:"#06B6D4",liquid:true},money_market:{l:"Money Market",icon:"💰",c:"#14B8A6",liquid:true},retirement:{l:"Retirement / 401k",icon:"🎯",c:"#8B5CF6",invest:true},ira:{l:"IRA",icon:"📊",c:"#7C3AED",invest:true},brokerage:{l:"Brokerage / Investment",icon:"📈",c:"#10B981",invest:true},other:{l:"Other",icon:"💼",c:"#94A3B8"}};
const LOAN_META={vehicle:{l:"Vehicle Loan",icon:"🚗",c:"#F97316"},student:{l:"Student Loan",icon:"🎓",c:"#3B82F6"},personal:{l:"Personal Loan",icon:"💼",c:"#8B5CF6"},mortgage:{l:"Mortgage",icon:"🏠",c:"#059669"},business:{l:"Business Loan",icon:"🏢",c:"#06B6D4"},other:{l:"Other Loan",icon:"💰",c:"#94A3B8"}};
const ACCA=Object.keys(ACCT_META);
const LOKA=Object.keys(LOAN_META);
const CP=["#4472C4","#ED7D31","#FFC000","#70AD47","#FF0000","#5B9BD5","#C00000","#9DC3E6","#F4B942","#A9D18E","#8E44AD","#2ECC71","#E74C3C","#3498DB","#1ABC9C","#E91E63","#00BCD4","#FF5722","#C9A84C","#607D8B"];
const PC=["#3B82F6","#10B981","#F59E0B","#8B5CF6","#06B6D4","#F97316","#84CC16","#E11D48"];
// v0.29.0 — `payUrl` is the new canonical field for service checkout links.
// Defaults are empty per service; advisor configures via Settings → Services & Stripe Links.
// Existing data: settings.stripeLinks[id] still works via the svcPayUrl() helper.
// Free services (insurance-consult) keep payUrl empty by design — "Pay now" disables.
const SVCS=[{id:"initial-checkup",icon:"🩺",en:"Initial Financial Checkup",es:"Chequeo Financiero Inicial",price:"$149",payUrl:"",desc:"Full snapshot review of your income, debts, savings, and financial goals.",descEs:"Revisión completa de ingresos, deudas, ahorros y metas financieras."},{id:"client-checkup",icon:"🔁",en:"Financial Checkup — Golden Anchor Client",es:"Chequeo Financiero — Cliente Golden Anchor",price:"$99",payUrl:"",desc:"Returning-client snapshot review. Tracks progress against previous plan.",descEs:"Revisión para clientes existentes. Compara contra el plan anterior."},{id:"quarterly-review",icon:"📊",en:"Quarterly Financial Review",es:"Revisión Financiera Trimestral",price:"$199",payUrl:"",desc:"Deeper quarterly review of cash flow, debt strategy, and goal progress.",descEs:"Revisión trimestral de flujo de caja, deudas y progreso de metas."},{id:"strategy-session",icon:"🎯",en:"Strategy Session: Home / Job / Budget",es:"Sesión Estratégica: Hogar / Trabajo / Presupuesto",price:"$129",payUrl:"",desc:"Targeted session for one major decision: a home purchase, a job change, or a budget reset.",descEs:"Sesión enfocada en una decisión clave: compra de casa, cambio de trabajo, o reinicio de presupuesto."},{id:"monthly-lite",icon:"💎",en:"Monthly Lite Financial Support",es:"Soporte Financiero Mensual Lite",price:"$49/mo",payUrl:"",desc:"Ongoing monthly support: brief check-ins, message-based Q&A, and accountability.",descEs:"Soporte mensual continuo: chequeos breves, preguntas por mensaje, y acompañamiento."},{id:"monthly-lite-plus",icon:"💎",en:"Monthly Lite Financial Support and 1 more",es:"Soporte Financiero Mensual Lite y 1 más",price:"$79/mo",payUrl:"",desc:"Lite support plus one Strategy Session add-on per month.",descEs:"Soporte Lite más una Sesión Estratégica adicional al mes."},{id:"annual-bundle",icon:"🏆",en:"Annual Financial Bundle",es:"Paquete Financiero Anual",price:"$499/yr",payUrl:"",desc:"Annual package: 4 quarterly reviews plus priority strategy sessions and a year-end report.",descEs:"Paquete anual: 4 revisiones trimestrales, sesiones estratégicas prioritarias, e informe de fin de año."},{id:"insurance-consult",icon:"🛡️",en:"Insurance Advisory (Free Consult)",es:"Asesoría de Seguros (Consulta Gratis)",price:"Free",payUrl:"",desc:"Life, health, and supplemental insurance review. Free first consult — commission-paid by carrier if you bind.",descEs:"Revisión de seguros de vida, salud, y suplementarios. Primera consulta gratis — comisión pagada por la aseguradora si contrata."},{id:"donation",icon:"💚",en:"Donation",es:"Donación",price:"Any amount",payUrl:"",desc:"Support Golden Anchor — donations are not financial services and do not establish an advisory relationship.",descEs:"Apoya Golden Anchor — las donaciones no son servicios financieros y no establecen una relación de asesoría."}];
// v0.29.0 — Read payUrl with fallback chain. Stored-in-settings (stripeLinks[id])
// wins over catalog defaults so the advisor can configure links without code changes.
// Free services (price === "Free") never return a payUrl — "Pay now" should disable.
const svcPayUrl=(svc,settings)=>{if(!svc||svc.price==="Free")return "";return settings?.stripeLinks?.[svc.id]||svc.payUrl||svc.stripeUrl||"";};
const DEF_PORT_RATES={conservative:5.5,growth:8.5,aggressive:11.0};
const TICKER_META={
  FXAIX:{name:"Fidelity 500 Index",desc:"Tracks S&P 500 — broad U.S. large-cap core holding.",cat:"US Large Cap"},
  VOO:{name:"Vanguard S&P 500 ETF",desc:"Tracks S&P 500 — broad U.S. large-cap core holding.",cat:"US Large Cap"},
  FXNAX:{name:"Fidelity US Bond Index",desc:"Total U.S. investment-grade bond market — stability & income.",cat:"Bonds"},
  VBTLX:{name:"Vanguard Total Bond",desc:"Total U.S. investment-grade bond market — stability & income.",cat:"Bonds"},
  FSPSX:{name:"Fidelity International Index",desc:"Developed-market ex-US equities — global diversification.",cat:"International"},
  VEA:{name:"Vanguard FTSE Developed Markets",desc:"Developed-market ex-US equities — global diversification.",cat:"International"},
  FSMAX:{name:"Fidelity Extended Market",desc:"U.S. mid- and small-cap equities — higher growth potential.",cat:"US Mid/Small Cap"},
  VXF:{name:"Vanguard Extended Market ETF",desc:"U.S. mid- and small-cap equities — higher growth potential.",cat:"US Mid/Small Cap"},
  VGT:{name:"Vanguard Information Tech ETF",desc:"Concentrated U.S. technology sector exposure — higher volatility.",cat:"Sector"},
  FTEC:{name:"Fidelity MSCI Tech Index",desc:"Concentrated U.S. technology sector exposure — higher volatility.",cat:"Sector"},
  SPAXX:{name:"Fidelity Government MMF",desc:"Money market fund — liquid cash position for stability.",cat:"Cash"},
  VMFXX:{name:"Vanguard Federal Money Market",desc:"Money market fund — liquid cash position for stability.",cat:"Cash"}
};
const PORTFOLIOS={conservative:{nameKey:"conservative",risk:"Low",color:"#10B981",holdings:[{ticker:"FXAIX",alt:"VOO",pct:30},{ticker:"FXNAX",alt:"VBTLX",pct:40},{ticker:"FSPSX",alt:"VEA",pct:15},{ticker:"SPAXX",alt:"VMFXX",pct:15}]},growth:{nameKey:"growth",risk:"Medium",color:"#3B82F6",holdings:[{ticker:"FXAIX",alt:"VOO",pct:50},{ticker:"FSMAX",alt:"VXF",pct:15},{ticker:"FSPSX",alt:"VEA",pct:15},{ticker:"FXNAX",alt:"VBTLX",pct:20}]},aggressive:{nameKey:"aggressive",risk:"High",color:"#F59E0B",holdings:[{ticker:"FXAIX",alt:"VOO",pct:40},{ticker:"FSMAX",alt:"VXF",pct:20},{ticker:"VGT",alt:"FTEC",pct:25},{ticker:"FSPSX",alt:"VEA",pct:15}]}};
const ALT_PACKS=[{id:"tech",label:"📱 Tech",stocks:[{ticker:"NVDA",alt:"SMH",name:"NVIDIA",pct:10,desc:"AI/GPU leader."},{ticker:"AAPL",alt:"QQQ",name:"Apple",pct:10,desc:"Mega-cap tech."},{ticker:"MSFT",alt:"IGV",name:"Microsoft",pct:10,desc:"Cloud + AI."}]},{id:"bonds",label:"🏦 Bonds",stocks:[{ticker:"BND",alt:"AGG",name:"Total Bond Market",pct:10,desc:"Investment grade."},{ticker:"TLT",alt:"EDV",name:"Long-Term Treasury",pct:10,desc:"20+ yr."},{ticker:"VCSH",alt:"IGSB",name:"Short-Term Corp",pct:10,desc:"Short duration."}]},{id:"gold",label:"🥇 Gold",stocks:[{ticker:"GLD",alt:"IAU",name:"Gold ETF",pct:10,desc:"Physical gold."},{ticker:"PHYS",alt:"SGOL",name:"Physical Gold Trust",pct:10,desc:"Inflation hedge."},{ticker:"NEM",alt:"WPM",name:"Newmont Mining",pct:10,desc:"Gold mining."}]}];
// Main Packages view: the three standard portfolios, reusable + editable per-client
const MAIN_PACKS=[{id:"conservative",label:"🛡️ Conservative Package",portKey:"conservative"},{id:"growth",label:"📈 Growth Package",portKey:"growth"},{id:"aggressive",label:"🚀 Aggressive Package",portKey:"aggressive"}];
const MS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const MS_ES=["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];
const ML_ES=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const mLabel=(label,lang)=>{if(!label||lang!=="es")return label;const parts=String(label).split(" ");if(parts.length<2)return label;const i=MS.indexOf(parts[0]);if(i<0)return label;return MS_ES[i]+" "+parts.slice(1).join(" ");};
const ML=["January","February","March","April","May","June","July","August","September","October","November","December"];
const CERTS=["Master of Business Administration (MBA)","Bachelor of Business Administration (BBA)","FMVA — Financial Modeling & Valuation Analyst","FPWMP — Financial Planning & Wealth Management Professional","FL0215 — Florida Life & Health Insurance License"];
const PHYS_CATS=[{v:"Real Estate",icon:"🏠"},{v:"Vehicle",icon:"🚗"},{v:"Precious Metals",icon:"🥇"},{v:"Business",icon:"🏢"},{v:"Collectible",icon:"🎨"},{v:"Other",icon:"💼"}];
const ACCT_L_ES={checking:"Cuenta Corriente",savings:"Ahorros",money_market:"Mercado Monetario",retirement:"Retiro / 401k",ira:"IRA",brokerage:"Corretaje / Inversión",other:"Otro"};
const LOAN_L_ES={vehicle:"Préstamo de Vehículo",student:"Préstamo Estudiantil",personal:"Préstamo Personal",mortgage:"Hipoteca",business:"Préstamo Comercial",other:"Otro Préstamo"};
const PHYS_L_ES={"Real Estate":"Bienes Raíces","Vehicle":"Vehículo","Precious Metals":"Metales Preciosos","Business":"Negocio","Collectible":"Coleccionable","Other":"Otro"};
const _gaLang=()=>(typeof window!=="undefined"&&window.__GA_LANG)||"en";
const acctL=k=>(_gaLang()==="es"&&ACCT_L_ES[k])||(ACCT_META[k]&&ACCT_META[k].l)||k;
const loanL=k=>(_gaLang()==="es"&&LOAN_L_ES[k])||(LOAN_META[k]&&LOAN_META[k].l)||k;
const physL=v=>(_gaLang()==="es"&&PHYS_L_ES[v])||v;

const DEF_SETTINGS={baseFontSize:14,appZoom:1,ig:"golden_anchor_inc",advisorName:"Mauricio Hernandez",advisorEmail:"mauricio@goldenanchor.life",noContactDays:30,darkAccent:GOLD,lightAccent:"#C9A84C",darkBg:"#111827",darkCard:"#1F2937",lightBg:"#FAF6EC",lightCard:"#FFFFFF",hideNumbers:false,lang:"en",isDark:true,reminderAdvisor:{noContact:true,highDebt:true,promoExpiring:true,debtIncreasing:false},stripeLinks:{"initial-checkup":"https://buy.stripe.com/fZu3cw5NUaLF9ZW81NfrW04","client-checkup":"https://buy.stripe.com/fZu4gAfou4nh1tq6XJfrW03","quarterly-review":"https://buy.stripe.com/cNieVe6RY7ztdc86XJfrW05","strategy-session":"https://buy.stripe.com/14A9AU1xE2f98VSgyjfrW02","monthly-lite":"https://buy.stripe.com/9B68wQ9062f91tq95RfrW00","monthly-lite-plus":"https://buy.stripe.com/eVq3cw1xEg5Z8VS3LxfrW07","annual-bundle":"https://buy.stripe.com/aFa00kekqg5Z7ROa9VfrW01","insurance-consult":"","donation":"https://buy.stripe.com/14A7sMgsyg5ZgokeqbfrW06"},lastBackupVerified:null,dashboardSlots:["incomeVsSpending","sankey","netWorthDonut"],chartCustomizations:{}};

export { ACCT_META, LOAN_META, ACCA, LOKA, CP, PC, SVCS, svcPayUrl, DEF_PORT_RATES, TICKER_META, PORTFOLIOS, ALT_PACKS, MAIN_PACKS, MS, MS_ES, ML_ES, mLabel, ML, CERTS, PHYS_CATS, ACCT_L_ES, LOAN_L_ES, PHYS_L_ES, _gaLang, acctL, loanL, physL, DEF_SETTINGS };
