// aiExport.js — MD-J (v0.75.3): "make sure reports are AI-readable so I can share
// them with an AI to make the advisement faster" (owner). Serializes EVERYTHING the
// client record holds (per the golden-anchor-logic §6 field dictionary) into clean
// structured markdown an LLM can reason over. Pure data — no JSX (D-29-style module).
// explicit .js extension so the module also runs under plain node (testability)
import { toM, sumB, sumN, sumMin, cardMoInt, totalA, totalL, liquidA, payM } from "./finance.js";

const $ = (n) => "$" + Math.round(+n || 0).toLocaleString("en-US");
const pct = (n) => (Math.round((+n || 0) * 10) / 10) + "%";
const line = (label, val) => `- ${label}: ${val}`;

function gaClientAIText(client) {
  const c = client || {};
  const L = [];
  const push = (s) => L.push(s);
  const net = sumN(c.incomeStreams || []);
  const bills = sumB(c.bills || []);
  const minDebt = sumMin(c.cards || []);
  const loanPay = (c.loans || []).reduce((s, l) => s + (+l.payment || 0), 0);
  const tA = totalA(c), tL = totalL(c), liquid = liquidA(c);
  const cardDebt = (c.cards || []).reduce((s, x) => s + (+x.balance || 0), 0);
  const loanDebt = (c.loans || []).reduce((s, x) => s + (+x.balance || 0), 0);
  const leftover = net - bills - minDebt - loanPay;
  const efMonths = bills > 0 ? liquid / bills : 0;
  const dsr = net > 0 ? ((minDebt + loanPay) / net) * 100 : 0;

  push("# Client financial profile — " + ((c.firstName || "") + " " + (c.lastName || "")).trim());
  push("_Generated by Golden Anchor for AI-assisted advisement. Educational coaching context — not investment advice._");
  push("");
  push("## Identity & household");
  push(line("Name", ((c.firstName || "") + " " + (c.lastName || "")).trim() || "—"));
  if (c.partnerFirst) push(line("Partner", (c.partnerFirst + " " + (c.partnerLast || "")).trim()));
  push(line("Email", c.email || "—"));
  if (c.phone) push(line("Phone", c.phone));
  if (c.dob) push(line("Date of birth", c.dob));
  push(line("Client type", c.clientType || "—"));
  if (c.servicePlan || c.accountPlan) push(line("Plan", c.servicePlan || c.accountPlan));
  push("");
  push("## Key metrics (monthly unless noted)");
  push(line("Net income", $(net)));
  push(line("Bills", $(bills)));
  push(line("Debt minimums (cards + loans)", $(minDebt + loanPay)));
  push(line("Leftover after bills & minimums", $(leftover)));
  push(line("Debt-service ratio", pct(dsr) + " (target < 36%)"));
  push(line("Savings rate", net > 0 ? pct((leftover / net) * 100) : "—"));
  push(line("Total assets", $(tA)));
  push(line("Total liabilities", $(tL)));
  push(line("Net worth", $(tA - tL)));
  push(line("Liquid savings", $(liquid)));
  push(line("Emergency fund", (Math.round(efMonths * 10) / 10) + " months of bills (target " + (c.efMonths || 3) + ")"));
  push("");
  push("## Income streams");
  (c.incomeStreams || []).forEach(s => push(line(s.label || "Income", $(toM(+s.net || 0, s.freq)) + "/mo (" + (s.freq || "monthly") + (s.gross ? ", gross " + $(s.gross) : "") + ")")));
  if (!(c.incomeStreams || []).length) push("- none recorded");
  push("");
  push("## Monthly bills");
  (c.bills || []).filter(b => b.active !== false).forEach(b => push(line(b.name || "Bill", $(toM(+b.cost || 0, b.freq)) + "/mo (due day " + (b.dueDay || "?") + (b.cat ? ", " + b.cat : "") + ")")));
  if (!(c.bills || []).length) push("- none recorded");
  push("");
  push("## Credit cards");
  (c.cards || []).forEach(cd => {
    push(line(cd.name || "Card", "balance " + $(cd.balance) + ", APR " + (cd.apr || 0) + "%, limit " + $(cd.limit || 0) + ", min " + $(payM(cd)) + "/mo, interest " + $(cardMoInt(cd)) + "/mo" + (cd.dueDay ? ", due day " + cd.dueDay : "")));
    (cd.promos || []).forEach(p => push("  - promo: " + (p.desc || "promo") + " " + (p.apr != null ? p.apr + "% APR" : "") + (p.ends ? " ends " + p.ends : "")));
  });
  if (!(c.cards || []).length) push("- none recorded");
  push("");
  push("## Loans");
  (c.loans || []).forEach(l => push(line(l.name || "Loan", (l.type || "loan") + ", balance " + $(l.balance) + ", rate " + (l.rate || 0) + "%, payment " + $(l.payment || 0) + "/mo" + (l.term ? ", term " + l.term : ""))));
  if (!(c.loans || []).length) push("- none recorded");
  push("");
  push("## Accounts & savings");
  (c.accounts || []).forEach(a => push(line(a.name || "Account", (a.type || "account") + " " + $(a.value) + (a.apy ? " @ " + a.apy + "% APY" : ""))));
  (c.customAssets || []).forEach(a => push(line(a.name || "Asset", $(a.value))));
  if (!(c.accounts || []).length && !(c.customAssets || []).length) push("- none recorded");
  push("");
  if ((c.physicalAssets || []).length) {
    push("## Physical assets");
    (c.physicalAssets || []).forEach(p => push(line(p.name || "Asset", (p.cat || "") + " " + $(p.value))));
    push("");
  }
  if ((c.investments || []).length || c.portfolio) {
    push("## Investments");
    (c.investments || []).forEach(iv => push(line(iv.ticker || iv.name || "Holding", $(iv.value || 0) + (iv.shares ? " (" + iv.shares + " sh)" : ""))));
    if (c.portfolio) push(line("Portfolio model", typeof c.portfolio === "string" ? c.portfolio : JSON.stringify(c.portfolio)));
    push("");
  }
  push("## Goals");
  const notes = c.notes || {};
  if (notes.goals) push(line("Stated goals", String(notes.goals).replace(/\n/g, " / ")));
  if (notes.shortTerm) push(line("Short term", notes.shortTerm));
  if (notes.midTerm) push(line("Mid term", notes.midTerm));
  if (notes.longTerm) push(line("Long term", notes.longTerm));
  if (!notes.goals && !notes.shortTerm && !notes.midTerm && !notes.longTerm) push("- none recorded");
  push("");
  const snaps = Array.isArray(c.monthSnapshots) ? c.monthSnapshots : [];
  if (snaps.length) {
    push("## Month-by-month history (label | debt | savings | net worth)");
    snaps.slice(-24).forEach(s => push("- " + (s.label || "?") + " | " + $(s.debt || 0) + " | " + $(s.savings || 0) + (s.netWorth != null ? " | " + $(s.netWorth) : "")));
    push("");
  }
  if (c.insuranceInterests && (c.insuranceInterests.health || c.insuranceInterests.car)) {
    push("## Insurance interests");
    if (c.insuranceInterests.health) push("- requested a FREE health-insurance consultation");
    if (c.insuranceInterests.car) push("- interested in car insurance help");
    push("");
  }
  push("---");
  push("_Ask of the AI: review ratios vs targets, flag the highest-interest debts, suggest a payoff order (avalanche vs snowball with these real numbers), and list 3 plain-language next steps for this household._");
  return L.join("\n");
}

export { gaClientAIText };
